### PR TITLE
use NewClientWith for tests

### PR DESCRIPTION
**Pull request by ghost**
this just switches to use NewClientWith for tests

### CODE REVIEW

**Comment by ghost** [comment]
This wasn't really needed. I can make use of `NewClientWith`

**Comment by thebaer** [comment]
This looked like a reasonable change... why wasn't it needed?

**Comment by ghost** [comment]
Because NewClientWith already provides the same functionality. I think 😁

**Comment by ghost** [comment]
The changes look like just using NewClientWith for tests but the first commit here was to change the new client methods to take a URL parameter, https://github.com/writeas/go-writeas/pull/17/commits/d622687fa8c1a0518bf533a33db6fd362c2b43e6.

I can open a new cleaner PR with just the test changes if you like.

**Pull request closed without merging**
